import '@/app/global.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ApolloProviders } from '../apollo_provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ApolloProviders>{children}</ApolloProviders>
      </body>
    </html>
  );
}
